spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fantasy-football-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: fantasy-football-engine

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

